#include "cairo-events.h"
#include <X11/Xlib.h>

const char *const events[] = {
	[KeyPress] = "KeyPress",
	[KeyRelease] = "KeyRelease",
	[ButtonPress] = "ButtonPress",
	[ButtonRelease] = "ButtonRelease",
	[MotionNotify] = "MotionNotify",
	[EnterNotify] = "EnterNotify",
	[LeaveNotify] = "LeaveNotify",
	[FocusIn] = "FocusIn",
	[FocusOut] = "FocusOut",
	[KeymapNotify] = "KeymapNotify",
	[Expose] = "Expose",
	[GraphicsExpose] = "GraphicsExpose",
	[NoExpose] = "NoExpose",
	[VisibilityNotify] = "VisibilityNotify",
	[CreateNotify] = "CreateNotify",
	[DestroyNotify] = "DestroyNotify",
	[UnmapNotify] = "UnmapNotify",
	[MapNotify] = "MapNotify",
	[MapRequest] = "MapRequest",
	[ReparentNotify] = "ReparentNotify",
	[ConfigureNotify] = "ConfigureNotify",
	[ConfigureRequest] = "ConfigureRequest",
	[GravityNotify] = "GravityNotify",
	[ResizeRequest] = "ResizeRequest",
	[CirculateNotify] = "CirculateNotify",
	[CirculateRequest] = "CirculateRequest",
	[PropertyNotify] = "PropertyNotify",
	[SelectionClear] = "SelectionClear",
	[SelectionRequest] = "SelectionRequest",
	[SelectionNotify] = "SelectionNotify",
	[ColormapNotify] = "ColormapNotify",
	[ClientMessage] = "ClientMessage",
	[MappingNotify] = "MappingNotify",
	[LASTEvent] = "LASTEvent"
};
